server {
    listen 8080;
    server_name _;
    location /clash.yaml {
        alias /usr/share/nginx/html/clash.yaml;
        default_type text/plain;
    }
    location / {
        return 404;
    }
}