server {
    listen 8080;
    server_name _;
    location /reality-subscribe {
        default_type text/plain;
        alias /usr/share/nginx/html/subscribe;
    }
    location /reality-link {
        default_type text/plain;
        alias /usr/share/nginx/html/client-link.txt;
    }
    location / {
        return 404;
    }
}
