server {
    listen 8080;
    server_name _;
    location /subscribe {
        default_type text/plain;
        alias /usr/share/nginx/html/subscribe;
    }
    location /hysteria2-link {
        default_type text/plain;
        alias /usr/share/nginx/html/hysteria2-link;
    }
    location /hysteria2-client.yaml {
        default_type text/plain;
        alias /usr/share/nginx/html/hysteria2-client.yaml;
    }
    location /reality-link {
        default_type text/plain;
        alias /usr/share/nginx/html/reality-link;
    }
    location /speed-100m.bin {
        default_type application/octet-stream;
        alias /usr/share/nginx/html/speed-100m.bin;
    }
    location /config.json {
        alias /usr/share/nginx/html/config.json;
        default_type application/json;
    }
    location / {
        return 404;
    }
}
